language: python

python:
  - "3.7"
  - "3.8"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE=radioscraper.settings.test

before_script:
  - createdb -U postgres radioscraper_test
  - python manage.py migrate

script: pytest
